(((lambda (Y)
    ((lambda (cadr)
       ((lambda (map)
          (lambda (xs)
            ((map cadr) xs)))
        (lambda (f)
          (Y (lambda (map*)
               (lambda (coll)
                 (if coll
                     (cons (f (car coll))
                           (map* (cdr coll)))
                     nil)))))))
     (lambda (c)
       (car (cdr c)))))
  (lambda (f)
    ((lambda (x)
       (f (lambda (y) ((x x) y))))
     (lambda (x)
       (f (lambda (y) ((x x) y)))))))
 '((a b c) (d e f)))
